### ISSUE TITLE
Problems with compilation(on Noetic-Ros)

### ISSUE THREAD

**Issue by BandyKenny** [OctoMap/octomap_mapping#116]
I installed octomap-ros on the terminal,
Then we start compiling octomap_mapping,
Now the following error appears, but I don't know how to solve it:
`Linking CXX executable /home/robot/catkin_ws/devel/lib/octomap_server/octomap_tracking_server_node 
/usr/bin/ld: /home/robot/catkin_ws/devel/lib/liboctomap_server.so: undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)' 
collect2: error: ld returned 1 exit status 
make[2]: *** [octomap_mapping/octomap_server/CMakeFiles/octomap_tracking_server_node.dir/build.make:206：/home/robot/catkin_ws/devel/lib/octomap_server/octomap_tracking_server_node] 错误 1 
make[1]: *** [CMakeFiles/Makefile2:6509：octomap_mapping/octomap_server/CMakeFiles/octomap_tracking_server_node.dir/all] 错误 2 
make: *** [Makefile:141：all] 错误 2 
Invoking "make -j1" failed `

**Comment by wxmerkt** [comment]
Hi BandyKenny, it is hard to know where your error is coming from. We do test with octomap and octomap_ros from binaries in our CI setup - i.e. this should work. It might be due to your local installation. Try cleaning the workspace, checking the environment variables/what is sourced and recompiling.
Hope this helps
